// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: markets.proto

package marketPB

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _markets_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Market with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Market) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Market with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in MarketMultiError, or nil if none found.
func (m *Market) ValidateAll() error {
	return m.validate(true)
}

func (m *Market) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetMarketName()); l < 2 || l > 256 {
		err := MarketValidationError{
			field:  "MarketName",
			reason: "value length must be between 2 and 256 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetGoodsId()); err != nil {
		err = MarketValidationError{
			field:  "GoodsId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetMarketId()); err != nil {
		err = MarketValidationError{
			field:  "MarketId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for MarketAccessibility

	// no validation rules for MarketTtl

	if len(errors) > 0 {
		return MarketMultiError(errors)
	}

	return nil
}

func (m *Market) _validateUuid(uuid string) error {
	if matched := _markets_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// MarketMultiError is an error wrapping multiple validation errors returned by
// Market.ValidateAll() if the designated constraints aren't met.
type MarketMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MarketMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MarketMultiError) AllErrors() []error { return m }

// MarketValidationError is the validation error returned by Market.Validate if
// the designated constraints aren't met.
type MarketValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MarketValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MarketValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MarketValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MarketValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MarketValidationError) ErrorName() string { return "MarketValidationError" }

// Error satisfies the builtin error interface
func (e MarketValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMarket.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MarketValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MarketValidationError{}

// Validate checks the field values on ViewMarketRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ViewMarketRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ViewMarketRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ViewMarketRequestMultiError, or nil if none found.
func (m *ViewMarketRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ViewMarketRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetViewMarketRequest()); l < 2 || l > 256 {
		err := ViewMarketRequestValidationError{
			field:  "ViewMarketRequest",
			reason: "value length must be between 2 and 256 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ViewMarketRequestMultiError(errors)
	}

	return nil
}

// ViewMarketRequestMultiError is an error wrapping multiple validation errors
// returned by ViewMarketRequest.ValidateAll() if the designated constraints
// aren't met.
type ViewMarketRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ViewMarketRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ViewMarketRequestMultiError) AllErrors() []error { return m }

// ViewMarketRequestValidationError is the validation error returned by
// ViewMarketRequest.Validate if the designated constraints aren't met.
type ViewMarketRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ViewMarketRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ViewMarketRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ViewMarketRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ViewMarketRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ViewMarketRequestValidationError) ErrorName() string {
	return "ViewMarketRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ViewMarketRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sViewMarketRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ViewMarketRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ViewMarketRequestValidationError{}

// Validate checks the field values on ViewMarketResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ViewMarketResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ViewMarketResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ViewMarketResponseMultiError, or nil if none found.
func (m *ViewMarketResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ViewMarketResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetViewMarketResponse()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ViewMarketResponseValidationError{
					field:  "ViewMarketResponse",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ViewMarketResponseValidationError{
					field:  "ViewMarketResponse",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetViewMarketResponse()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ViewMarketResponseValidationError{
				field:  "ViewMarketResponse",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ViewMarketResponseMultiError(errors)
	}

	return nil
}

// ViewMarketResponseMultiError is an error wrapping multiple validation errors
// returned by ViewMarketResponse.ValidateAll() if the designated constraints
// aren't met.
type ViewMarketResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ViewMarketResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ViewMarketResponseMultiError) AllErrors() []error { return m }

// ViewMarketResponseValidationError is the validation error returned by
// ViewMarketResponse.Validate if the designated constraints aren't met.
type ViewMarketResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ViewMarketResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ViewMarketResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ViewMarketResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ViewMarketResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ViewMarketResponseValidationError) ErrorName() string {
	return "ViewMarketResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ViewMarketResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sViewMarketResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ViewMarketResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ViewMarketResponseValidationError{}

// Validate checks the field values on ViewMarketsAllRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ViewMarketsAllRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ViewMarketsAllRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ViewMarketsAllRequestMultiError, or nil if none found.
func (m *ViewMarketsAllRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ViewMarketsAllRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for PageSize

	// no validation rules for PageToken

	if len(errors) > 0 {
		return ViewMarketsAllRequestMultiError(errors)
	}

	return nil
}

// ViewMarketsAllRequestMultiError is an error wrapping multiple validation
// errors returned by ViewMarketsAllRequest.ValidateAll() if the designated
// constraints aren't met.
type ViewMarketsAllRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ViewMarketsAllRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ViewMarketsAllRequestMultiError) AllErrors() []error { return m }

// ViewMarketsAllRequestValidationError is the validation error returned by
// ViewMarketsAllRequest.Validate if the designated constraints aren't met.
type ViewMarketsAllRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ViewMarketsAllRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ViewMarketsAllRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ViewMarketsAllRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ViewMarketsAllRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ViewMarketsAllRequestValidationError) ErrorName() string {
	return "ViewMarketsAllRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ViewMarketsAllRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sViewMarketsAllRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ViewMarketsAllRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ViewMarketsAllRequestValidationError{}

// Validate checks the field values on ViewMarketsAllResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ViewMarketsAllResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ViewMarketsAllResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ViewMarketsAllResponseMultiError, or nil if none found.
func (m *ViewMarketsAllResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ViewMarketsAllResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMarkets() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ViewMarketsAllResponseValidationError{
						field:  fmt.Sprintf("Markets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ViewMarketsAllResponseValidationError{
						field:  fmt.Sprintf("Markets[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ViewMarketsAllResponseValidationError{
					field:  fmt.Sprintf("Markets[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ViewMarketsAllResponseMultiError(errors)
	}

	return nil
}

// ViewMarketsAllResponseMultiError is an error wrapping multiple validation
// errors returned by ViewMarketsAllResponse.ValidateAll() if the designated
// constraints aren't met.
type ViewMarketsAllResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ViewMarketsAllResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ViewMarketsAllResponseMultiError) AllErrors() []error { return m }

// ViewMarketsAllResponseValidationError is the validation error returned by
// ViewMarketsAllResponse.Validate if the designated constraints aren't met.
type ViewMarketsAllResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ViewMarketsAllResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ViewMarketsAllResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ViewMarketsAllResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ViewMarketsAllResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ViewMarketsAllResponseValidationError) ErrorName() string {
	return "ViewMarketsAllResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ViewMarketsAllResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sViewMarketsAllResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ViewMarketsAllResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ViewMarketsAllResponseValidationError{}
