version: '3.9'

services:

  postgres:
    image: postgres:18-alpine3.22-dev
    environment:
      POSTGRES_USER: postgres
      #я знаю что так нельзя хранить имя и пароль, тем более передавать в виде файлов, но проект маленький
      # и переусложнять его такими штуками как правильное сохранение секретов и т.д - мне показалось излишним
      POSTGRES_PASSWORD: postgres
      POSTGRES_DM: gRPCbigAppDB
    ports:
      - "5432:5432"

  redis:
    image: redis:8-debian13-dev
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus
    volumes:
      - #тут прсто примастил на сам контейнер, если создавать как сохранение ещё куда-то то могу потупить чуть подольше
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"