global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:2112']

  - job_name: 'market-service'
    static_configs:
      - targets: ['market-service:2113']
