// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: client.proto

package clientPB

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Roles int32

const (
	Roles_UNAUTHORISED_USER Roles = 0
	Roles_FREE_PLAN_USER    Roles = 1
	Roles_PRO_PLAN_USER     Roles = 2
	Roles_ADMIN             Roles = 3
)

// Enum value maps for Roles.
var (
	Roles_name = map[int32]string{
		0: "UNAUTHORISED_USER",
		1: "FREE_PLAN_USER",
		2: "PRO_PLAN_USER",
		3: "ADMIN",
	}
	Roles_value = map[string]int32{
		"UNAUTHORISED_USER": 0,
		"FREE_PLAN_USER":    1,
		"PRO_PLAN_USER":     2,
		"ADMIN":             3,
	}
)

func (x Roles) Enum() *Roles {
	p := new(Roles)
	*p = x
	return p
}

func (x Roles) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Roles) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[0].Descriptor()
}

func (Roles) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[0]
}

func (x Roles) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Roles.Descriptor instead.
func (Roles) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPassword  string `protobuf:"bytes,3,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	UserRole      Roles  `protobuf:"varint,4,opt,name=user_role,json=userRole,proto3,enum=auth.Roles" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

func (x *User) GetUserRole() Roles {
	if x != nil {
		return x.UserRole
	}
	return Roles_UNAUTHORISED_USER
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPassword  string `protobuf:"bytes,2,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	UserRole      Roles  `protobuf:"varint,3,opt,name=user_role,json=userRole,proto3,enum=auth.Roles" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterRequest) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

func (x *RegisterRequest) GetUserRole() Roles {
	if x != nil {
		return x.UserRole
	}
	return Roles_UNAUTHORISED_USER
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPassword  string                 `protobuf:"bytes,2,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginRequest) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TokenTtl      int64                  `protobuf:"varint,2,opt,name=token_ttl,json=tokenTtl,proto3" json:"token_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetTokenTtl() int64 {
	if x != nil {
		return x.TokenTtl
	}
	return 0
}

type PlanChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserRole      Roles  `protobuf:"varint,2,opt,name=user_role,json=userRole,proto3,enum=auth.Roles" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanChangeRequest) Reset() {
	*x = PlanChangeRequest{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanChangeRequest) ProtoMessage() {}

func (x *PlanChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanChangeRequest.ProtoReflect.Descriptor instead.
func (*PlanChangeRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *PlanChangeRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PlanChangeRequest) GetUserRole() Roles {
	if x != nil {
		return x.UserRole
	}
	return Roles_UNAUTHORISED_USER
}

type PlanChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserRole      Roles  `protobuf:"varint,2,opt,name=user_role,json=userRole,proto3,enum=auth.Roles" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanChangeResponse) Reset() {
	*x = PlanChangeResponse{}
	mi := &file_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanChangeResponse) ProtoMessage() {}

func (x *PlanChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanChangeResponse.ProtoReflect.Descriptor instead.
func (*PlanChangeResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *PlanChangeResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PlanChangeResponse) GetUserRole() Roles {
	if x != nil {
		return x.UserRole
	}
	return Roles_UNAUTHORISED_USER
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\x04auth\x1a\x17validate/validate.proto\"\xe1\x01\n" +
	"\x04User\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12@\n" +
	"\tuser_name\x18\x02 \x01(\tB#\xfaB r\x1e\x10\x04\x18\x102\x18^[A-Za-z]+( [A-Za-z]+)*$R\buserName\x12>\n" +
	"\ruser_password\x18\x03 \x01(\tB\x19\xfaB\x16r\x14\x10\b\x18H2\x0e^[\\x21-\\x7E]+$R\fuserPassword\x124\n" +
	"\tuser_role\x18\x04 \x01(\x0e2\v.auth.RolesB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\buserRole\"\xc9\x01\n" +
	"\x0fRegisterRequest\x12@\n" +
	"\tuser_name\x18\x01 \x01(\tB#\xfaB r\x1e\x10\x04\x18\x102\x18^[A-Za-z]+( [A-Za-z]+)*$R\buserName\x12>\n" +
	"\ruser_password\x18\x02 \x01(\tB\x19\xfaB\x16r\x14\x10\b\x18H2\x0e^[\\x21-\\x7E]+$R\fuserPassword\x124\n" +
	"\tuser_role\x18\x03 \x01(\x0e2\v.auth.RolesB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\buserRole\"\x90\x01\n" +
	"\fLoginRequest\x12@\n" +
	"\tuser_name\x18\x01 \x01(\tB#\xfaB r\x1e\x10\x04\x18\x102\x18^[A-Za-z]+( [A-Za-z]+)*$R\buserName\x12>\n" +
	"\ruser_password\x18\x02 \x01(\tB\x19\xfaB\x16r\x14\x10\b\x18H2\x0e^[\\x21-\\x7E]+$R\fuserPassword\"A\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\ttoken_ttl\x18\x02 \x01(\x03R\btokenTtl\"\x8b\x01\n" +
	"\x11PlanChangeRequest\x12@\n" +
	"\tuser_name\x18\x01 \x01(\tB#\xfaB r\x1e\x10\x04\x18\x102\x18^[A-Za-z]+( [A-Za-z]+)*$R\buserName\x124\n" +
	"\tuser_role\x18\x02 \x01(\x0e2\v.auth.RolesB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\buserRole\"\x8c\x01\n" +
	"\x12PlanChangeResponse\x12@\n" +
	"\tuser_name\x18\x01 \x01(\tB#\xfaB r\x1e\x10\x04\x18\x102\x18^[A-Za-z]+( [A-Za-z]+)*$R\buserName\x124\n" +
	"\tuser_role\x18\x02 \x01(\x0e2\v.auth.RolesB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\buserRole*P\n" +
	"\x05Roles\x12\x15\n" +
	"\x11UNAUTHORISED_USER\x10\x00\x12\x12\n" +
	"\x0eFREE_PLAN_USER\x10\x01\x12\x11\n" +
	"\rPRO_PLAN_USER\x10\x02\x12\t\n" +
	"\x05ADMIN\x10\x032\xc2\x01\n" +
	"\vAuthService\x12=\n" +
	"\x10UserRegistration\x12\x15.auth.RegisterRequest\x1a\x12.auth.AuthResponse\x123\n" +
	"\tUserLogin\x12\x12.auth.LoginRequest\x1a\x12.auth.AuthResponse\x12?\n" +
	"\n" +
	"PlanChange\x12\x17.auth.PlanChangeRequest\x1a\x18.auth.PlanChangeResponseB!Z\x1fgRPCbigapp/Proto/protoPB;clientb\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_client_proto_goTypes = []any{
	(Roles)(0),                 // 0: auth.Roles
	(*User)(nil),               // 1: auth.User
	(*RegisterRequest)(nil),    // 2: auth.RegisterRequest
	(*LoginRequest)(nil),       // 3: auth.LoginRequest
	(*AuthResponse)(nil),       // 4: auth.AuthResponse
	(*PlanChangeRequest)(nil),  // 5: auth.PlanChangeRequest
	(*PlanChangeResponse)(nil), // 6: auth.PlanChangeResponse
}
var file_client_proto_depIdxs = []int32{
	0, // 0: auth.User.user_role:type_name -> auth.Roles
	0, // 1: auth.RegisterRequest.user_role:type_name -> auth.Roles
	0, // 2: auth.PlanChangeRequest.user_role:type_name -> auth.Roles
	0, // 3: auth.PlanChangeResponse.user_role:type_name -> auth.Roles
	2, // 4: auth.AuthService.UserRegistration:input_type -> auth.RegisterRequest
	3, // 5: auth.AuthService.UserLogin:input_type -> auth.LoginRequest
	5, // 6: auth.AuthService.PlanChange:input_type -> auth.PlanChangeRequest
	4, // 7: auth.AuthService.UserRegistration:output_type -> auth.AuthResponse
	4, // 8: auth.AuthService.UserLogin:output_type -> auth.AuthResponse
	6, // 9: auth.AuthService.PlanChange:output_type -> auth.PlanChangeResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		EnumInfos:         file_client_proto_enumTypes,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
