// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: client.proto

package clientPB

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _client_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on User with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *User) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on User with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in UserMultiError, or nil if none found.
func (m *User) ValidateAll() error {
	return m.validate(true)
}

func (m *User) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = UserValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserName()); l < 4 || l > 16 {
		err := UserValidationError{
			field:  "UserName",
			reason: "value length must be between 4 and 16 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_User_UserName_Pattern.MatchString(m.GetUserName()) {
		err := UserValidationError{
			field:  "UserName",
			reason: "value does not match regex pattern \"^[A-Za-z]+( [A-Za-z]+)*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserPassword()); l < 8 || l > 72 {
		err := UserValidationError{
			field:  "UserPassword",
			reason: "value length must be between 8 and 72 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_User_UserPassword_Pattern.MatchString(m.GetUserPassword()) {
		err := UserValidationError{
			field:  "UserPassword",
			reason: "value does not match regex pattern \"^[\\\\x21-\\\\x7E]+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _User_UserRole_NotInLookup[m.GetUserRole()]; ok {
		err := UserValidationError{
			field:  "UserRole",
			reason: "value must not be in list [UNAUTHORISED_USER]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := Roles_name[int32(m.GetUserRole())]; !ok {
		err := UserValidationError{
			field:  "UserRole",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UserMultiError(errors)
	}

	return nil
}

func (m *User) _validateUuid(uuid string) error {
	if matched := _client_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// UserMultiError is an error wrapping multiple validation errors returned by
// User.ValidateAll() if the designated constraints aren't met.
type UserMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserMultiError) AllErrors() []error { return m }

// UserValidationError is the validation error returned by User.Validate if the
// designated constraints aren't met.
type UserValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserValidationError) ErrorName() string { return "UserValidationError" }

// Error satisfies the builtin error interface
func (e UserValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUser.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserValidationError{}

var _User_UserName_Pattern = regexp.MustCompile("^[A-Za-z]+( [A-Za-z]+)*$")

var _User_UserPassword_Pattern = regexp.MustCompile("^[\\x21-\\x7E]+$")

var _User_UserRole_NotInLookup = map[Roles]struct{}{
	0: {},
}

// Validate checks the field values on RegisterRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RegisterRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterRequestMultiError, or nil if none found.
func (m *RegisterRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetUserName()); l < 4 || l > 16 {
		err := RegisterRequestValidationError{
			field:  "UserName",
			reason: "value length must be between 4 and 16 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_RegisterRequest_UserName_Pattern.MatchString(m.GetUserName()) {
		err := RegisterRequestValidationError{
			field:  "UserName",
			reason: "value does not match regex pattern \"^[A-Za-z]+( [A-Za-z]+)*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserPassword()); l < 8 || l > 72 {
		err := RegisterRequestValidationError{
			field:  "UserPassword",
			reason: "value length must be between 8 and 72 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_RegisterRequest_UserPassword_Pattern.MatchString(m.GetUserPassword()) {
		err := RegisterRequestValidationError{
			field:  "UserPassword",
			reason: "value does not match regex pattern \"^[\\\\x21-\\\\x7E]+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _RegisterRequest_UserRole_NotInLookup[m.GetUserRole()]; ok {
		err := RegisterRequestValidationError{
			field:  "UserRole",
			reason: "value must not be in list [UNAUTHORISED_USER]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := Roles_name[int32(m.GetUserRole())]; !ok {
		err := RegisterRequestValidationError{
			field:  "UserRole",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RegisterRequestMultiError(errors)
	}

	return nil
}

// RegisterRequestMultiError is an error wrapping multiple validation errors
// returned by RegisterRequest.ValidateAll() if the designated constraints
// aren't met.
type RegisterRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterRequestMultiError) AllErrors() []error { return m }

// RegisterRequestValidationError is the validation error returned by
// RegisterRequest.Validate if the designated constraints aren't met.
type RegisterRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterRequestValidationError) ErrorName() string { return "RegisterRequestValidationError" }

// Error satisfies the builtin error interface
func (e RegisterRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterRequestValidationError{}

var _RegisterRequest_UserName_Pattern = regexp.MustCompile("^[A-Za-z]+( [A-Za-z]+)*$")

var _RegisterRequest_UserPassword_Pattern = regexp.MustCompile("^[\\x21-\\x7E]+$")

var _RegisterRequest_UserRole_NotInLookup = map[Roles]struct{}{
	0: {},
}

// Validate checks the field values on LoginRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LoginRequestMultiError, or
// nil if none found.
func (m *LoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetUserName()); l < 4 || l > 16 {
		err := LoginRequestValidationError{
			field:  "UserName",
			reason: "value length must be between 4 and 16 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_LoginRequest_UserName_Pattern.MatchString(m.GetUserName()) {
		err := LoginRequestValidationError{
			field:  "UserName",
			reason: "value does not match regex pattern \"^[A-Za-z]+( [A-Za-z]+)*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserPassword()); l < 8 || l > 72 {
		err := LoginRequestValidationError{
			field:  "UserPassword",
			reason: "value length must be between 8 and 72 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_LoginRequest_UserPassword_Pattern.MatchString(m.GetUserPassword()) {
		err := LoginRequestValidationError{
			field:  "UserPassword",
			reason: "value does not match regex pattern \"^[\\\\x21-\\\\x7E]+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return LoginRequestMultiError(errors)
	}

	return nil
}

// LoginRequestMultiError is an error wrapping multiple validation errors
// returned by LoginRequest.ValidateAll() if the designated constraints aren't met.
type LoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginRequestMultiError) AllErrors() []error { return m }

// LoginRequestValidationError is the validation error returned by
// LoginRequest.Validate if the designated constraints aren't met.
type LoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginRequestValidationError) ErrorName() string { return "LoginRequestValidationError" }

// Error satisfies the builtin error interface
func (e LoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginRequestValidationError{}

var _LoginRequest_UserName_Pattern = regexp.MustCompile("^[A-Za-z]+( [A-Za-z]+)*$")

var _LoginRequest_UserPassword_Pattern = regexp.MustCompile("^[\\x21-\\x7E]+$")

// Validate checks the field values on AuthResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AuthResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AuthResponseMultiError, or
// nil if none found.
func (m *AuthResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for TokenTtl

	if len(errors) > 0 {
		return AuthResponseMultiError(errors)
	}

	return nil
}

// AuthResponseMultiError is an error wrapping multiple validation errors
// returned by AuthResponse.ValidateAll() if the designated constraints aren't met.
type AuthResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthResponseMultiError) AllErrors() []error { return m }

// AuthResponseValidationError is the validation error returned by
// AuthResponse.Validate if the designated constraints aren't met.
type AuthResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthResponseValidationError) ErrorName() string { return "AuthResponseValidationError" }

// Error satisfies the builtin error interface
func (e AuthResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthResponseValidationError{}

// Validate checks the field values on PlanChangeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PlanChangeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PlanChangeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PlanChangeRequestMultiError, or nil if none found.
func (m *PlanChangeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PlanChangeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetUserName()); l < 4 || l > 16 {
		err := PlanChangeRequestValidationError{
			field:  "UserName",
			reason: "value length must be between 4 and 16 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_PlanChangeRequest_UserName_Pattern.MatchString(m.GetUserName()) {
		err := PlanChangeRequestValidationError{
			field:  "UserName",
			reason: "value does not match regex pattern \"^[A-Za-z]+( [A-Za-z]+)*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _PlanChangeRequest_UserRole_NotInLookup[m.GetUserRole()]; ok {
		err := PlanChangeRequestValidationError{
			field:  "UserRole",
			reason: "value must not be in list [UNAUTHORISED_USER]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := Roles_name[int32(m.GetUserRole())]; !ok {
		err := PlanChangeRequestValidationError{
			field:  "UserRole",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PlanChangeRequestMultiError(errors)
	}

	return nil
}

// PlanChangeRequestMultiError is an error wrapping multiple validation errors
// returned by PlanChangeRequest.ValidateAll() if the designated constraints
// aren't met.
type PlanChangeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PlanChangeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PlanChangeRequestMultiError) AllErrors() []error { return m }

// PlanChangeRequestValidationError is the validation error returned by
// PlanChangeRequest.Validate if the designated constraints aren't met.
type PlanChangeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PlanChangeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PlanChangeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PlanChangeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PlanChangeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PlanChangeRequestValidationError) ErrorName() string {
	return "PlanChangeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PlanChangeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPlanChangeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PlanChangeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PlanChangeRequestValidationError{}

var _PlanChangeRequest_UserName_Pattern = regexp.MustCompile("^[A-Za-z]+( [A-Za-z]+)*$")

var _PlanChangeRequest_UserRole_NotInLookup = map[Roles]struct{}{
	0: {},
}

// Validate checks the field values on PlanChangeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PlanChangeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PlanChangeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PlanChangeResponseMultiError, or nil if none found.
func (m *PlanChangeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PlanChangeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetUserName()); l < 4 || l > 16 {
		err := PlanChangeResponseValidationError{
			field:  "UserName",
			reason: "value length must be between 4 and 16 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_PlanChangeResponse_UserName_Pattern.MatchString(m.GetUserName()) {
		err := PlanChangeResponseValidationError{
			field:  "UserName",
			reason: "value does not match regex pattern \"^[A-Za-z]+( [A-Za-z]+)*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _PlanChangeResponse_UserRole_NotInLookup[m.GetUserRole()]; ok {
		err := PlanChangeResponseValidationError{
			field:  "UserRole",
			reason: "value must not be in list [UNAUTHORISED_USER]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := Roles_name[int32(m.GetUserRole())]; !ok {
		err := PlanChangeResponseValidationError{
			field:  "UserRole",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PlanChangeResponseMultiError(errors)
	}

	return nil
}

// PlanChangeResponseMultiError is an error wrapping multiple validation errors
// returned by PlanChangeResponse.ValidateAll() if the designated constraints
// aren't met.
type PlanChangeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PlanChangeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PlanChangeResponseMultiError) AllErrors() []error { return m }

// PlanChangeResponseValidationError is the validation error returned by
// PlanChangeResponse.Validate if the designated constraints aren't met.
type PlanChangeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PlanChangeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PlanChangeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PlanChangeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PlanChangeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PlanChangeResponseValidationError) ErrorName() string {
	return "PlanChangeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PlanChangeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPlanChangeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PlanChangeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PlanChangeResponseValidationError{}

var _PlanChangeResponse_UserName_Pattern = regexp.MustCompile("^[A-Za-z]+( [A-Za-z]+)*$")

var _PlanChangeResponse_UserRole_NotInLookup = map[Roles]struct{}{
	0: {},
}

// Validate checks the field values on IsAdminRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *IsAdminRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IsAdminRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in IsAdminRequestMultiError,
// or nil if none found.
func (m *IsAdminRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *IsAdminRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetUserName()); l < 4 || l > 16 {
		err := IsAdminRequestValidationError{
			field:  "UserName",
			reason: "value length must be between 4 and 16 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_IsAdminRequest_UserName_Pattern.MatchString(m.GetUserName()) {
		err := IsAdminRequestValidationError{
			field:  "UserName",
			reason: "value does not match regex pattern \"^[A-Za-z]+( [A-Za-z]+)*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserPassword()); l < 8 || l > 72 {
		err := IsAdminRequestValidationError{
			field:  "UserPassword",
			reason: "value length must be between 8 and 72 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_IsAdminRequest_UserPassword_Pattern.MatchString(m.GetUserPassword()) {
		err := IsAdminRequestValidationError{
			field:  "UserPassword",
			reason: "value does not match regex pattern \"^[\\\\x21-\\\\x7E]+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return IsAdminRequestMultiError(errors)
	}

	return nil
}

// IsAdminRequestMultiError is an error wrapping multiple validation errors
// returned by IsAdminRequest.ValidateAll() if the designated constraints
// aren't met.
type IsAdminRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IsAdminRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IsAdminRequestMultiError) AllErrors() []error { return m }

// IsAdminRequestValidationError is the validation error returned by
// IsAdminRequest.Validate if the designated constraints aren't met.
type IsAdminRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IsAdminRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IsAdminRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IsAdminRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IsAdminRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IsAdminRequestValidationError) ErrorName() string { return "IsAdminRequestValidationError" }

// Error satisfies the builtin error interface
func (e IsAdminRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIsAdminRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IsAdminRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IsAdminRequestValidationError{}

var _IsAdminRequest_UserName_Pattern = regexp.MustCompile("^[A-Za-z]+( [A-Za-z]+)*$")

var _IsAdminRequest_UserPassword_Pattern = regexp.MustCompile("^[\\x21-\\x7E]+$")

// Validate checks the field values on IsAdminResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *IsAdminResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IsAdminResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IsAdminResponseMultiError, or nil if none found.
func (m *IsAdminResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *IsAdminResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for IsAdmin

	if len(errors) > 0 {
		return IsAdminResponseMultiError(errors)
	}

	return nil
}

// IsAdminResponseMultiError is an error wrapping multiple validation errors
// returned by IsAdminResponse.ValidateAll() if the designated constraints
// aren't met.
type IsAdminResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IsAdminResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IsAdminResponseMultiError) AllErrors() []error { return m }

// IsAdminResponseValidationError is the validation error returned by
// IsAdminResponse.Validate if the designated constraints aren't met.
type IsAdminResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IsAdminResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IsAdminResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IsAdminResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IsAdminResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IsAdminResponseValidationError) ErrorName() string { return "IsAdminResponseValidationError" }

// Error satisfies the builtin error interface
func (e IsAdminResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIsAdminResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IsAdminResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IsAdminResponseValidationError{}
