// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: markets.proto

package protoPB

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Market struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MarketName          string                 `protobuf:"bytes,1,opt,name=market_name,json=marketName,proto3" json:"market_name,omitempty"`
	GoodsId             string                 `protobuf:"bytes,2,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	MarketId            string                 `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	MarketAccessibility bool                   `protobuf:"varint,4,opt,name=market_accessibility,json=marketAccessibility,proto3" json:"market_accessibility,omitempty"`
	MarketTtl           int64                  `protobuf:"varint,5,opt,name=market_ttl,json=marketTtl,proto3" json:"market_ttl,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_markets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_markets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_markets_proto_rawDescGZIP(), []int{0}
}

func (x *Market) GetMarketName() string {
	if x != nil {
		return x.MarketName
	}
	return ""
}

func (x *Market) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *Market) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Market) GetMarketAccessibility() bool {
	if x != nil {
		return x.MarketAccessibility
	}
	return false
}

func (x *Market) GetMarketTtl() int64 {
	if x != nil {
		return x.MarketTtl
	}
	return 0
}

type ViewMarketRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ViewMarketRequest string                 `protobuf:"bytes,1,opt,name=view_market_request,json=viewMarketRequest,proto3" json:"view_market_request,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ViewMarketRequest) Reset() {
	*x = ViewMarketRequest{}
	mi := &file_markets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketRequest) ProtoMessage() {}

func (x *ViewMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_markets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketRequest) Descriptor() ([]byte, []int) {
	return file_markets_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketRequest) GetViewMarketRequest() string {
	if x != nil {
		return x.ViewMarketRequest
	}
	return ""
}

type ViewMarketResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ViewMarketResponse *Market                `protobuf:"bytes,1,opt,name=view_market_response,json=viewMarketResponse,proto3" json:"view_market_response,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ViewMarketResponse) Reset() {
	*x = ViewMarketResponse{}
	mi := &file_markets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketResponse) ProtoMessage() {}

func (x *ViewMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_markets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketResponse) Descriptor() ([]byte, []int) {
	return file_markets_proto_rawDescGZIP(), []int{2}
}

func (x *ViewMarketResponse) GetViewMarketResponse() *Market {
	if x != nil {
		return x.ViewMarketResponse
	}
	return nil
}

type ViewMarketsAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsAllRequest) Reset() {
	*x = ViewMarketsAllRequest{}
	mi := &file_markets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsAllRequest) ProtoMessage() {}

func (x *ViewMarketsAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_markets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsAllRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsAllRequest) Descriptor() ([]byte, []int) {
	return file_markets_proto_rawDescGZIP(), []int{3}
}

func (x *ViewMarketsAllRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ViewMarketsAllRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ViewMarketsAllRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ViewMarketsAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*Market              `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsAllResponse) Reset() {
	*x = ViewMarketsAllResponse{}
	mi := &file_markets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsAllResponse) ProtoMessage() {}

func (x *ViewMarketsAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_markets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsAllResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsAllResponse) Descriptor() ([]byte, []int) {
	return file_markets_proto_rawDescGZIP(), []int{4}
}

func (x *ViewMarketsAllResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *ViewMarketsAllResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_markets_proto protoreflect.FileDescriptor

const file_markets_proto_rawDesc = "" +
	"\n" +
	"\rmarkets.proto\x12\amarkets\x1a\x17validate/validate.proto\"\xd3\x01\n" +
	"\x06Market\x12+\n" +
	"\vmarket_name\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\x80\x02R\n" +
	"marketName\x12#\n" +
	"\bgoods_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\agoodsId\x12%\n" +
	"\tmarket_id\x18\x03 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\bmarketId\x121\n" +
	"\x14market_accessibility\x18\x04 \x01(\bR\x13marketAccessibility\x12\x1d\n" +
	"\n" +
	"market_ttl\x18\x05 \x01(\x03R\tmarketTtl\"O\n" +
	"\x11ViewMarketRequest\x12:\n" +
	"\x13view_market_request\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\x80\x02R\x11viewMarketRequest\"W\n" +
	"\x12ViewMarketResponse\x12A\n" +
	"\x14view_market_response\x18\x01 \x01(\v2\x0f.markets.MarketR\x12viewMarketResponse\"i\n" +
	"\x15ViewMarketsAllRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"k\n" +
	"\x16ViewMarketsAllResponse\x12)\n" +
	"\amarkets\x18\x01 \x03(\v2\x0f.markets.MarketR\amarkets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xb6\x01\n" +
	"\x15SpotInstrumentService\x12J\n" +
	"\x0fViewMarketsByID\x12\x1a.markets.ViewMarketRequest\x1a\x1b.markets.ViewMarketResponse\x12Q\n" +
	"\x0eViewMarketsAll\x12\x1e.markets.ViewMarketsAllRequest\x1a\x1f.markets.ViewMarketsAllResponseB!Z\x1fgRPCbigapp/Proto/protoPB;marketb\x06proto3"

var (
	file_markets_proto_rawDescOnce sync.Once
	file_markets_proto_rawDescData []byte
)

func file_markets_proto_rawDescGZIP() []byte {
	file_markets_proto_rawDescOnce.Do(func() {
		file_markets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_markets_proto_rawDesc), len(file_markets_proto_rawDesc)))
	})
	return file_markets_proto_rawDescData
}

var file_markets_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_markets_proto_goTypes = []any{
	(*Market)(nil),                 // 0: markets.Market
	(*ViewMarketRequest)(nil),      // 1: markets.ViewMarketRequest
	(*ViewMarketResponse)(nil),     // 2: markets.ViewMarketResponse
	(*ViewMarketsAllRequest)(nil),  // 3: markets.ViewMarketsAllRequest
	(*ViewMarketsAllResponse)(nil), // 4: markets.ViewMarketsAllResponse
}
var file_markets_proto_depIdxs = []int32{
	0, // 0: markets.ViewMarketResponse.view_market_response:type_name -> markets.Market
	0, // 1: markets.ViewMarketsAllResponse.markets:type_name -> markets.Market
	1, // 2: markets.SpotInstrumentService.ViewMarketsByID:input_type -> markets.ViewMarketRequest
	3, // 3: markets.SpotInstrumentService.ViewMarketsAll:input_type -> markets.ViewMarketsAllRequest
	2, // 4: markets.SpotInstrumentService.ViewMarketsByID:output_type -> markets.ViewMarketResponse
	4, // 5: markets.SpotInstrumentService.ViewMarketsAll:output_type -> markets.ViewMarketsAllResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_markets_proto_init() }
func file_markets_proto_init() {
	if File_markets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_markets_proto_rawDesc), len(file_markets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_markets_proto_goTypes,
		DependencyIndexes: file_markets_proto_depIdxs,
		MessageInfos:      file_markets_proto_msgTypes,
	}.Build()
	File_markets_proto = out.File
	file_markets_proto_goTypes = nil
	file_markets_proto_depIdxs = nil
}
