// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: order.proto

package order

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_UNREGISTERED_STATUS          OrderStatus = 0
	OrderStatus_ORDER_REJECTED               OrderStatus = 1
	OrderStatus_ORDER_CREATED                OrderStatus = 2
	OrderStatus_ORDER_RESERVED               OrderStatus = 3
	OrderStatus_ORDER_IN_PROCESS_OF_DELIVERY OrderStatus = 4
	OrderStatus_ORDER_HAS_BEEN_DELIVERED     OrderStatus = 5
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "UNREGISTERED_STATUS",
		1: "ORDER_REJECTED",
		2: "ORDER_CREATED",
		3: "ORDER_RESERVED",
		4: "ORDER_IN_PROCESS_OF_DELIVERY",
		5: "ORDER_HAS_BEEN_DELIVERED",
	}
	OrderStatus_value = map[string]int32{
		"UNREGISTERED_STATUS":          0,
		"ORDER_REJECTED":               1,
		"ORDER_CREATED":                2,
		"ORDER_RESERVED":               3,
		"ORDER_IN_PROCESS_OF_DELIVERY": 4,
		"ORDER_HAS_BEEN_DELIVERED":     5,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MarketId      string                 `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Price         *money.Money           `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Amount        *decimal.Decimal       `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderStatus   OrderStatus            `protobuf:"varint,6,opt,name=order_status,json=orderStatus,proto3,enum=order.OrderStatus" json:"order_status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Order) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Order) GetAmount() *decimal.Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Order) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_UNREGISTERED_STATUS
}

func (x *Order) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Amount        *decimal.Decimal       `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Price         *money.Money           `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	OrderStatus   OrderStatus            `protobuf:"varint,4,opt,name=order_status,json=orderStatus,proto3,enum=order.OrderStatus" json:"order_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *CreateOrderRequest) GetAmount() *decimal.Decimal {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateOrderRequest) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *CreateOrderRequest) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_UNREGISTERED_STATUS
}

type CreateOrderResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CreateOrderResponse *Order                 `protobuf:"bytes,1,opt,name=create_order_response,json=createOrderResponse,proto3" json:"create_order_response,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetCreateOrderResponse() *Order {
	if x != nil {
		return x.CreateOrderResponse
	}
	return nil
}

type OrderStatusByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusByIDRequest) Reset() {
	*x = OrderStatusByIDRequest{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusByIDRequest) ProtoMessage() {}

func (x *OrderStatusByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusByIDRequest.ProtoReflect.Descriptor instead.
func (*OrderStatusByIDRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderStatusByIDRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type OrderStatusByIDResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrderStatusResponse *Order                 `protobuf:"bytes,1,opt,name=order_status_response,json=orderStatusResponse,proto3" json:"order_status_response,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrderStatusByIDResponse) Reset() {
	*x = OrderStatusByIDResponse{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusByIDResponse) ProtoMessage() {}

func (x *OrderStatusByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusByIDResponse.ProtoReflect.Descriptor instead.
func (*OrderStatusByIDResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderStatusByIDResponse) GetOrderStatusResponse() *Order {
	if x != nil {
		return x.OrderStatusResponse
	}
	return nil
}

type OrderStatusAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusAllRequest) Reset() {
	*x = OrderStatusAllRequest{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusAllRequest) ProtoMessage() {}

func (x *OrderStatusAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusAllRequest.ProtoReflect.Descriptor instead.
func (*OrderStatusAllRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderStatusAllRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *OrderStatusAllRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type OrderStatusAllResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AllOrdersStatusesResponse []*Order               `protobuf:"bytes,1,rep,name=all_orders_statuses_response,json=allOrdersStatusesResponse,proto3" json:"all_orders_statuses_response,omitempty"`
	NextPageToken             string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *OrderStatusAllResponse) Reset() {
	*x = OrderStatusAllResponse{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusAllResponse) ProtoMessage() {}

func (x *OrderStatusAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusAllResponse.ProtoReflect.Descriptor instead.
func (*OrderStatusAllResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *OrderStatusAllResponse) GetAllOrdersStatusesResponse() []*Order {
	if x != nil {
		return x.AllOrdersStatusesResponse
	}
	return nil
}

func (x *OrderStatusAllResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type StreamOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrderRequest) Reset() {
	*x = StreamOrderRequest{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrderRequest) ProtoMessage() {}

func (x *StreamOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrderRequest.ProtoReflect.Descriptor instead.
func (*StreamOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *StreamOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\x1a\x17validate/validate.proto\x1a\x14validate/money.proto\x1a\x16validate/decimal.proto\"\xba\x02\n" +
	"\x05Order\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12#\n" +
	"\border_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aorderId\x12%\n" +
	"\tmarket_id\x18\x03 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\bmarketId\x122\n" +
	"\x05price\x18\x04 \x01(\v2\x12.google.type.MoneyB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05price\x12,\n" +
	"\x06amount\x18\x05 \x01(\v2\x14.google.type.DecimalR\x06amount\x12A\n" +
	"\forder_status\x18\x06 \x01(\x0e2\x12.order.OrderStatusB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\vorderStatus\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xe0\x01\n" +
	"\x12CreateOrderRequest\x12%\n" +
	"\tmarket_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\bmarketId\x12,\n" +
	"\x06amount\x18\x02 \x01(\v2\x14.google.type.DecimalR\x06amount\x122\n" +
	"\x05price\x18\x03 \x01(\v2\x12.google.type.MoneyB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05price\x12A\n" +
	"\forder_status\x18\x04 \x01(\x0e2\x12.order.OrderStatusB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\vorderStatus\"W\n" +
	"\x13CreateOrderResponse\x12@\n" +
	"\x15create_order_response\x18\x01 \x01(\v2\f.order.OrderR\x13createOrderResponse\"?\n" +
	"\x16OrderStatusByIDRequest\x12%\n" +
	"\tmarket_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\bmarketId\"[\n" +
	"\x17OrderStatusByIDResponse\x12@\n" +
	"\x15order_status_response\x18\x01 \x01(\v2\f.order.OrderR\x13orderStatusResponse\"S\n" +
	"\x15OrderStatusAllRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x8f\x01\n" +
	"\x16OrderStatusAllResponse\x12M\n" +
	"\x1call_orders_statuses_response\x18\x01 \x03(\v2\f.order.OrderR\x19allOrdersStatusesResponse\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"9\n" +
	"\x12StreamOrderRequest\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aorderId*\xa1\x01\n" +
	"\vOrderStatus\x12\x17\n" +
	"\x13UNREGISTERED_STATUS\x10\x00\x12\x12\n" +
	"\x0eORDER_REJECTED\x10\x01\x12\x11\n" +
	"\rORDER_CREATED\x10\x02\x12\x12\n" +
	"\x0eORDER_RESERVED\x10\x03\x12 \n" +
	"\x1cORDER_IN_PROCESS_OF_DELIVERY\x10\x04\x12\x1c\n" +
	"\x18ORDER_HAS_BEEN_DELIVERED\x10\x052\xce\x02\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x19.order.CreateOrderRequest\x1a\x1a.order.CreateOrderResponse\x12S\n" +
	"\x12GetOrderStatusByID\x12\x1d.order.OrderStatusByIDRequest\x1a\x1e.order.OrderStatusByIDResponse\x12Q\n" +
	"\x12StreamOrderUpdates\x12\x19.order.StreamOrderRequest\x1a\x1e.order.OrderStatusByIDResponse0\x01\x12P\n" +
	"\x11GetOrderStatusAll\x12\x1c.order.OrderStatusAllRequest\x1a\x1d.order.OrderStatusAllResponseB Z\x1egRPCbigapp/Proto/protoPB;orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_order_proto_goTypes = []any{
	(OrderStatus)(0),                // 0: order.OrderStatus
	(*Order)(nil),                   // 1: order.Order
	(*CreateOrderRequest)(nil),      // 2: order.CreateOrderRequest
	(*CreateOrderResponse)(nil),     // 3: order.CreateOrderResponse
	(*OrderStatusByIDRequest)(nil),  // 4: order.OrderStatusByIDRequest
	(*OrderStatusByIDResponse)(nil), // 5: order.OrderStatusByIDResponse
	(*OrderStatusAllRequest)(nil),   // 6: order.OrderStatusAllRequest
	(*OrderStatusAllResponse)(nil),  // 7: order.OrderStatusAllResponse
	(*StreamOrderRequest)(nil),      // 8: order.StreamOrderRequest
	(*money.Money)(nil),             // 9: google.type.Money
	(*decimal.Decimal)(nil),         // 10: google.type.Decimal
}
var file_order_proto_depIdxs = []int32{
	9,  // 0: order.Order.price:type_name -> google.type.Money
	10, // 1: order.Order.amount:type_name -> google.type.Decimal
	0,  // 2: order.Order.order_status:type_name -> order.OrderStatus
	10, // 3: order.CreateOrderRequest.amount:type_name -> google.type.Decimal
	9,  // 4: order.CreateOrderRequest.price:type_name -> google.type.Money
	0,  // 5: order.CreateOrderRequest.order_status:type_name -> order.OrderStatus
	1,  // 6: order.CreateOrderResponse.create_order_response:type_name -> order.Order
	1,  // 7: order.OrderStatusByIDResponse.order_status_response:type_name -> order.Order
	1,  // 8: order.OrderStatusAllResponse.all_orders_statuses_response:type_name -> order.Order
	2,  // 9: order.OrderService.CreateOrder:input_type -> order.CreateOrderRequest
	4,  // 10: order.OrderService.GetOrderStatusByID:input_type -> order.OrderStatusByIDRequest
	8,  // 11: order.OrderService.StreamOrderUpdates:input_type -> order.StreamOrderRequest
	6,  // 12: order.OrderService.GetOrderStatusAll:input_type -> order.OrderStatusAllRequest
	3,  // 13: order.OrderService.CreateOrder:output_type -> order.CreateOrderResponse
	5,  // 14: order.OrderService.GetOrderStatusByID:output_type -> order.OrderStatusByIDResponse
	5,  // 15: order.OrderService.StreamOrderUpdates:output_type -> order.OrderStatusByIDResponse
	7,  // 16: order.OrderService.GetOrderStatusAll:output_type -> order.OrderStatusAllResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		EnumInfos:         file_order_proto_enumTypes,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
