// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: markets.proto

package market

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpotInstrumentService_ViewMarketsByID_FullMethodName = "/markets.SpotInstrumentService/ViewMarketsByID"
	SpotInstrumentService_ViewMarketsAll_FullMethodName  = "/markets.SpotInstrumentService/ViewMarketsAll"
)

// SpotInstrumentServiceClient is the client API for SpotInstrumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpotInstrumentServiceClient interface {
	ViewMarketsByID(ctx context.Context, in *ViewMarketsByIDRequest, opts ...grpc.CallOption) (*ViewMarketsByIDResponse, error)
	ViewMarketsAll(ctx context.Context, in *ViewMarketsAllRequest, opts ...grpc.CallOption) (*ViewMarketsAllResponse, error)
}

type spotInstrumentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpotInstrumentServiceClient(cc grpc.ClientConnInterface) SpotInstrumentServiceClient {
	return &spotInstrumentServiceClient{cc}
}

func (c *spotInstrumentServiceClient) ViewMarketsByID(ctx context.Context, in *ViewMarketsByIDRequest, opts ...grpc.CallOption) (*ViewMarketsByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewMarketsByIDResponse)
	err := c.cc.Invoke(ctx, SpotInstrumentService_ViewMarketsByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotInstrumentServiceClient) ViewMarketsAll(ctx context.Context, in *ViewMarketsAllRequest, opts ...grpc.CallOption) (*ViewMarketsAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewMarketsAllResponse)
	err := c.cc.Invoke(ctx, SpotInstrumentService_ViewMarketsAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpotInstrumentServiceServer is the server API for SpotInstrumentService service.
// All implementations must embed UnimplementedSpotInstrumentServiceServer
// for forward compatibility.
type SpotInstrumentServiceServer interface {
	ViewMarketsByID(context.Context, *ViewMarketsByIDRequest) (*ViewMarketsByIDResponse, error)
	ViewMarketsAll(context.Context, *ViewMarketsAllRequest) (*ViewMarketsAllResponse, error)
	mustEmbedUnimplementedSpotInstrumentServiceServer()
}

// UnimplementedSpotInstrumentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpotInstrumentServiceServer struct{}

func (UnimplementedSpotInstrumentServiceServer) ViewMarketsByID(context.Context, *ViewMarketsByIDRequest) (*ViewMarketsByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ViewMarketsByID not implemented")
}
func (UnimplementedSpotInstrumentServiceServer) ViewMarketsAll(context.Context, *ViewMarketsAllRequest) (*ViewMarketsAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ViewMarketsAll not implemented")
}
func (UnimplementedSpotInstrumentServiceServer) mustEmbedUnimplementedSpotInstrumentServiceServer() {}
func (UnimplementedSpotInstrumentServiceServer) testEmbeddedByValue()                               {}

// UnsafeSpotInstrumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpotInstrumentServiceServer will
// result in compilation errors.
type UnsafeSpotInstrumentServiceServer interface {
	mustEmbedUnimplementedSpotInstrumentServiceServer()
}

func RegisterSpotInstrumentServiceServer(s grpc.ServiceRegistrar, srv SpotInstrumentServiceServer) {
	// If the following call panics, it indicates UnimplementedSpotInstrumentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpotInstrumentService_ServiceDesc, srv)
}

func _SpotInstrumentService_ViewMarketsByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewMarketsByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotInstrumentServiceServer).ViewMarketsByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotInstrumentService_ViewMarketsByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotInstrumentServiceServer).ViewMarketsByID(ctx, req.(*ViewMarketsByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpotInstrumentService_ViewMarketsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewMarketsAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotInstrumentServiceServer).ViewMarketsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotInstrumentService_ViewMarketsAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotInstrumentServiceServer).ViewMarketsAll(ctx, req.(*ViewMarketsAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpotInstrumentService_ServiceDesc is the grpc.ServiceDesc for SpotInstrumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpotInstrumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "markets.SpotInstrumentService",
	HandlerType: (*SpotInstrumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ViewMarketsByID",
			Handler:    _SpotInstrumentService_ViewMarketsByID_Handler,
		},
		{
			MethodName: "ViewMarketsAll",
			Handler:    _SpotInstrumentService_ViewMarketsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "markets.proto",
}
