// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: markets.proto

package market

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Market struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Enable        bool                   `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_markets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_markets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_markets_proto_rawDescGZIP(), []int{0}
}

func (x *Market) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Market) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type ViewMarketsByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	MarketId      string                 `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsByIDRequest) Reset() {
	*x = ViewMarketsByIDRequest{}
	mi := &file_markets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsByIDRequest) ProtoMessage() {}

func (x *ViewMarketsByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_markets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsByIDRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsByIDRequest) Descriptor() ([]byte, []int) {
	return file_markets_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketsByIDRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ViewMarketsByIDRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type ViewMarketsByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *Market                `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsByIDResponse) Reset() {
	*x = ViewMarketsByIDResponse{}
	mi := &file_markets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsByIDResponse) ProtoMessage() {}

func (x *ViewMarketsByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_markets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsByIDResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsByIDResponse) Descriptor() ([]byte, []int) {
	return file_markets_proto_rawDescGZIP(), []int{2}
}

func (x *ViewMarketsByIDResponse) GetMarket() *Market {
	if x != nil {
		return x.Market
	}
	return nil
}

type ViewMarketsAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsAllRequest) Reset() {
	*x = ViewMarketsAllRequest{}
	mi := &file_markets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsAllRequest) ProtoMessage() {}

func (x *ViewMarketsAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_markets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsAllRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketsAllRequest) Descriptor() ([]byte, []int) {
	return file_markets_proto_rawDescGZIP(), []int{3}
}

func (x *ViewMarketsAllRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ViewMarketsAllRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ViewMarketsAllRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ViewMarketsAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*Market              `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewMarketsAllResponse) Reset() {
	*x = ViewMarketsAllResponse{}
	mi := &file_markets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketsAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketsAllResponse) ProtoMessage() {}

func (x *ViewMarketsAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_markets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketsAllResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketsAllResponse) Descriptor() ([]byte, []int) {
	return file_markets_proto_rawDescGZIP(), []int{4}
}

func (x *ViewMarketsAllResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *ViewMarketsAllResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_markets_proto protoreflect.FileDescriptor

const file_markets_proto_rawDesc = "" +
	"\n" +
	"\rmarkets.proto\x12\amarkets\"=\n" +
	"\x06Market\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x16\n" +
	"\x06enable\x18\x02 \x01(\bR\x06enable\"K\n" +
	"\x16ViewMarketsByIDRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\"B\n" +
	"\x17ViewMarketsByIDResponse\x12'\n" +
	"\x06market\x18\x01 \x01(\v2\x0f.markets.MarketR\x06market\"i\n" +
	"\x15ViewMarketsAllRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"k\n" +
	"\x16ViewMarketsAllResponse\x12)\n" +
	"\amarkets\x18\x01 \x03(\v2\x0f.markets.MarketR\amarkets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xc0\x01\n" +
	"\x15SpotInstrumentService\x12T\n" +
	"\x0fViewMarketsByID\x12\x1f.markets.ViewMarketsByIDRequest\x1a .markets.ViewMarketsByIDResponse\x12Q\n" +
	"\x0eViewMarketsAll\x12\x1e.markets.ViewMarketsAllRequest\x1a\x1f.markets.ViewMarketsAllResponseB\tZ\a/marketb\x06proto3"

var (
	file_markets_proto_rawDescOnce sync.Once
	file_markets_proto_rawDescData []byte
)

func file_markets_proto_rawDescGZIP() []byte {
	file_markets_proto_rawDescOnce.Do(func() {
		file_markets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_markets_proto_rawDesc), len(file_markets_proto_rawDesc)))
	})
	return file_markets_proto_rawDescData
}

var file_markets_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_markets_proto_goTypes = []any{
	(*Market)(nil),                  // 0: markets.Market
	(*ViewMarketsByIDRequest)(nil),  // 1: markets.ViewMarketsByIDRequest
	(*ViewMarketsByIDResponse)(nil), // 2: markets.ViewMarketsByIDResponse
	(*ViewMarketsAllRequest)(nil),   // 3: markets.ViewMarketsAllRequest
	(*ViewMarketsAllResponse)(nil),  // 4: markets.ViewMarketsAllResponse
}
var file_markets_proto_depIdxs = []int32{
	0, // 0: markets.ViewMarketsByIDResponse.market:type_name -> markets.Market
	0, // 1: markets.ViewMarketsAllResponse.markets:type_name -> markets.Market
	1, // 2: markets.SpotInstrumentService.ViewMarketsByID:input_type -> markets.ViewMarketsByIDRequest
	3, // 3: markets.SpotInstrumentService.ViewMarketsAll:input_type -> markets.ViewMarketsAllRequest
	2, // 4: markets.SpotInstrumentService.ViewMarketsByID:output_type -> markets.ViewMarketsByIDResponse
	4, // 5: markets.SpotInstrumentService.ViewMarketsAll:output_type -> markets.ViewMarketsAllResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_markets_proto_init() }
func file_markets_proto_init() {
	if File_markets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_markets_proto_rawDesc), len(file_markets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_markets_proto_goTypes,
		DependencyIndexes: file_markets_proto_depIdxs,
		MessageInfos:      file_markets_proto_msgTypes,
	}.Build()
	File_markets_proto = out.File
	file_markets_proto_goTypes = nil
	file_markets_proto_depIdxs = nil
}
